# generated by mBlock5 for CyberPi
# codes make you happy

import mbot2, mbuild, event, time, cyberpi
import time
# initialize variables
srodkowanie = 0
cross_count = 0
prog = 0
cross_type = 0
predkosc = 0
wspolczynnik_skretu = 0
left_eng = 0
right_eng = 0

def line_follow_N_N_N(speed, steering, sensor):
    global srodkowanie, cross_count, prog, cross_type, predkosc, wspolczynnik_skretu, left_eng, right_eng
    left_eng = (speed - steering * sensor)
    right_eng = ((speed + steering * sensor)) * -1
    mbot2.EM_set_speed(left_eng,"EM1")
    mbot2.EM_set_speed(right_eng,"EM2")

def cross_logic():
    global srodkowanie, cross_count, prog, cross_type, predkosc, wspolczynnik_skretu, left_eng, right_eng
    if cross_type == mbuild.quad_rgb_sensor.get_line_sta("all", 1):
      cross_count = cross_count + 1

    else:
      cross_count = 0

    cross_type = mbuild.quad_rgb_sensor.get_line_sta("all", 1)

@event.start
def on_start():
    global srodkowanie, cross_count, prog, cross_type, predkosc, wspolczynnik_skretu, left_eng, right_eng
    srodkowanie = 7.7
    cross_count = 0
    prog = 3
    cross_type = 0
    predkosc = 25
    cross_count = 0.6
    while True:
      line_follow_N_N_N(25, 0.6, mbuild.quad_rgb_sensor.get_offset_track(1))
      if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 14:
        cross_logic()
        if cross_count == prog:
          mbot2.straight(srodkowanie)
          time.sleep(0.1)
          mbot2.turn(-90)

      if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 15:
        cross_logic()
        if cross_count == prog:
          mbot2.motor_stop("all")
          mbot2.straight(srodkowanie)
          if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 6:
            time.sleep(0.1)
            mbot2.turn(-90)
            cyberpi.audio.play('meow')

          else:
            time.sleep(0.1)
            mbot2.turn(-90)
            cyberpi.audio.play('annoyed')

      if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 7:
        cross_logic()
        if cross_count == prog:
          mbot2.straight(srodkowanie)
          time.sleep(0.1)
          mbot2.turn(90)

