# generated by mBlock5 for CyberPi
# codes make you happy

import mbuild, mbot2, event, time, cyberpi
# initialize variables
left_eng = 0
right_eng = 0
wspolczynnik_skretu = 0
predkosc = 0
index = 0
sciezka_list = []

def wybor_trasy():
  if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 14 or mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 15:
    mbot2.turn(-90)
    sciezka_list.append('L')

  if mbuild.quad_rgb_sensor.get_line_sta("middle", 1) == 3:
    mbot2.turn(90)
    sciezka_list.append('R')

  if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 7:
    sciezka_list.append('S')

  if mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 0:
    mbot2.turn(-180)
    mbot2.straight(10)
    sciezka_list.append('B')
    optymalizuj()

def line_follow_proportional_N_N_N(speed, steering, deviation):
  left_eng = -1 * ((speed + steering * deviation))
  right_eng = 1 * ((speed - steering * deviation))
  mbot2.drive_speed(left_eng, right_eng)

@event.start
def on_start():
    global left_eng, right_eng, wspolczynnik_skretu, predkosc, index, sciezka_list
    predkosc = 50
    wspolczynnik_skretu = 0.6
    while True:
      line_follow_proportional_N_N_N(1, 0.6, mbuild.quad_rgb_sensor.get_offset_track(1))
      if (mbuild.quad_rgb_sensor.is_color("blue","any",1)):
        mbot2.EM_stop("ALL")
        sprite.stop_this()

      if not mbuild.quad_rgb_sensor.get_line_sta("all", 1) == 6:
        mbot2.straight(10)
        wybor_trasy()

def optymalizuj():
  if len(sciezka_list) > 2:
    index = len(sciezka_list)
    if sciezka_list[(index - 2) - 1] == 'L' and sciezka_list[(index - 1) - 1] == 'B' and sciezka_list[index - 1] == 'R':
      del sciezka_list[(index - 2) - 1]
      del sciezka_list[(index - 1) - 1]
      del sciezka_list[index - 1]
      sciezka_list.append('B')

